### ISSUE TITLE
koop sample app not starting

### ISSUE THREAD

**Issue by mhogeweg** [koopjs/koop-sample-app#13]
following the instructions to install the koop sample app on windows, I'm getting the following error when accessing http://hogeweg.esri.com/koop. This while the node samples using express work just fine: http://hogeweg.esri.com/node/express.

```
iisnode encountered an error when processing the request.

HRESULT: 0x2
HTTP status: 500
HTTP subStatus: 1002
HTTP reason: Internal Server Error
You are receiving this HTTP 200 response because system.webServer/iisnode/@devErrorsEnabled configuration setting is 'true'.

In addition to the log of stdout and stderr of the node.exe process, consider using debugging and ETW traces to further diagnose the problem.

The last 64k of the output generated by the node.exe process to stderr is shown below:

Application has thrown an uncaught exception and is terminated:
Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (D:\My Documents\GitHub\koop-sample-app\server.js:1:77)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by jgravois** [comment]
do you see an `express` folder inside the `node_modules` folder next to `server.js` after running `npm install` (after cloning the repo?)

**Comment by mhogeweg** [comment]
thanks. that resolved it.

**Comment by jgravois** [comment]
happy to help.
