### ISSUE TITLE
Does not run

### ISSUE THREAD

**Issue by bmulcahy** [koopjs/koop-sample-app#41]
spatial reference module throws an error

```
node_modules\spatialreference\dist\index.js:25
SpatialReference.prototype.async wkidToWkt = function wkidToWkt (wkid, callback) {
                                 ^^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Projects\koop-sample-app\node_modules\koop-provider-agol\models\exporter.js:14:24)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! koop-sample-app@0.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the koop-sample-app@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Environments\nodejs\npm-cache\_logs\2018-07-24T17_17_47_518Z-debug.log
```

**Comment by rgwozdz** [comment]
@bmulcahy thanks for reporting this.  I have just released a patch to the [spatialreference](https://www.npmjs.com/package/spatialreference) that fixes this issue.  To get it into your koop-sample-provide you can do a `yarn upgrade`.
